-- DuckDB-style SQL examples for Linda Data analytics projects.
-- These examples assume you run DuckDB from the repository root.

-- 1. Read R built-in CSV exports generated by:
-- Rscript statistical-analytics/scripts/export_r_builtin_datasets.R
CREATE OR REPLACE VIEW mtcars AS
SELECT *
FROM read_csv_auto('statistical-analytics/data/r-builtins/mtcars.csv');

CREATE OR REPLACE VIEW airquality AS
SELECT *
FROM read_csv_auto('statistical-analytics/data/r-builtins/airquality.csv');

-- 2. Basic profiling.
SELECT
  COUNT(*) AS rows,
  COUNT(*) - COUNT(mpg) AS missing_mpg,
  AVG(mpg) AS avg_mpg,
  MIN(mpg) AS min_mpg,
  MAX(mpg) AS max_mpg
FROM mtcars;

-- 3. Correlation screening before regression.
SELECT
  corr(mpg, wt) AS corr_mpg_wt,
  corr(mpg, hp) AS corr_mpg_hp,
  corr(wt, disp) AS corr_wt_disp,
  corr(hp, disp) AS corr_hp_disp
FROM mtcars;

-- 4. DuckDB simple regression summaries.
SELECT
  regr_slope(mpg, wt) AS slope_wt,
  regr_intercept(mpg, wt) AS intercept_wt,
  regr_r2(mpg, wt) AS r2_wt
FROM mtcars;

-- 5. Create a regression-ready feature table.
CREATE OR REPLACE VIEW mtcars_model AS
SELECT
  mpg,
  wt,
  hp,
  disp,
  cyl,
  CASE WHEN am = 1 THEN 'manual' ELSE 'automatic' END AS transmission,
  CASE WHEN row_number() OVER (ORDER BY mpg, wt, hp) % 5 = 0 THEN 'test' ELSE 'train' END AS split
FROM mtcars
WHERE mpg IS NOT NULL
  AND wt IS NOT NULL
  AND hp IS NOT NULL
  AND disp IS NOT NULL;

-- 6. Train/test split audit.
SELECT
  split,
  COUNT(*) AS rows,
  AVG(mpg) AS avg_mpg,
  AVG(wt) AS avg_weight,
  AVG(hp) AS avg_horsepower
FROM mtcars_model
GROUP BY split
ORDER BY split;

-- 7. Missingness profile for a known small table.
SELECT 'Ozone' AS variable, COUNT(*) - COUNT(Ozone) AS missing_count, COUNT(*) AS rows FROM airquality
UNION ALL
SELECT 'Solar.R', COUNT(*) - COUNT("Solar.R"), COUNT(*) FROM airquality
UNION ALL
SELECT 'Wind', COUNT(*) - COUNT(Wind), COUNT(*) FROM airquality
UNION ALL
SELECT 'Temp', COUNT(*) - COUNT(Temp), COUNT(*) FROM airquality;

-- 8. Time feature example for API data after running download_open_data.py.
-- CREATE OR REPLACE VIEW bls_unemployment AS
-- SELECT *
-- FROM read_csv_auto('statistical-analytics/data/open-api/bls_unemployment_rate.csv');
--
-- SELECT
--   CAST(year AS INTEGER) AS year,
--   period,
--   CAST(value AS DOUBLE) AS unemployment_rate
-- FROM bls_unemployment
-- WHERE period <> 'M13'
-- ORDER BY year, period;
